version: "3.9"

services:
  namenode:

  datanode1:
    build: ./datanode
    container_name: datanode1
    environment:
      - DATANODE_ID=1
      - DATANODE_PORT=5001
    volumes:
      - ./datanode/storage # will have to change this depending on the architecture
    ports:
    - "5001:5001"
    networks:
    - dfsnet

  datanode2:
    build: ./datanode
    container_name: datanode2
    environment:
      - DATANODE_ID=2
      - DATANODE_PORT=5002
    volumes:
      - ./datanode/storage # will have to change this depending on the architecture
    ports:
    - "5002:5002"
    networks:
    - dfsnet

networks:
  dfsnet:
    driver: bridge